name: ncdc_practice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Riverpod
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Svg
  flutter_svg:

  uuid:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Code generator
  build_runner:
  freezed: ^2.3.2
  flutter_gen_runner: ^5.1.0+1

  # Static analysis
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/